Feat: liquid staking module sketch #LSC-267
lidofinance/lido-cosmos-hub-contracts pull request #13
Opened 2022-02-22 10:42 UTC by oopcode

2022-03-28 12:30 UTC, oopcode commented
a quick note (just thought about it) — what if we receive a big ass voucher that will mess up our distribution? we might want to consider redelegating or something.

2022-03-29 15:39 UTC, foxpy requested changes

2022-03-29 15:39 UTC, foxpy commented on contracts/lido_cosmos_hub/src/testing/tests.rs
> +fn new_tokenize_share(
Shouldn't this function be a static method of TokenizeShareRecord?

2022-04-02 16:59 UTC, oopcode commented on contracts/lido_cosmos_hub/src/tokenized.rs
> +// TODO: remove unwraps
todo comment

2022-04-02 17:03 UTC, oopcode commented on contracts/lido_cosmos_hub/src/tokenized.rs
> +    // Note: tokenized share denom looks like this:
not sure this comment is necessary anymore

2022-04-02 17:06 UTC, oopcode commented
what's up with the idea to get the redeemed amount inside the `reply` handler?

2022-04-05 09:18 UTC, pr0n00gler commented
> what's up with the idea to get the redeemed amount inside the `reply` handler?

I suggest to stick with the current version for now. When we will be able to test the contracts on more realistic infrastructure (our integration-test framework), we'll compare these two versions (current and with the 'reply'-handler) and choose a more accurate one (or with less gas consumption).

2022-04-05 12:44 UTC, foxpy approved these changes

2022-04-05 12:44 UTC, foxpy commented on packages/basset/src/hub.rs
> +    pub max_burn_ratio: Decimal,
We use both `max_burn_rate` and `max_burn_ratio` throughout code base. This is confusing.

2022-04-18 09:32 UTC, merged