feat: post-review fixes
lidofinance/lido-cosmos-hub-contracts pull request #15
Opened 2022-03-02 14:00 UTC by ratik

2022-03-03 08:54 UTC, pr0n00gler commented on contracts/lido_cosmos_validators_registry/src/common.rs
> -    Ok((amount_to_delegate, delegations))
I think we should check that `amount_to_delegate` equals to zero after the loop and if the value is greater than zero, revert the whole tx. This is impossible but I think one more check won't be excess since we always can do some changes in the distribution algorithm and forgot to add tests or smth. Wdyt?

2022-03-03 15:01 UTC, oopcode commented on contracts/lido_cosmos_rewards_dispatcher/README.md
> +All rewards from stAtom tokens (the share of all rewards proportional to the amount of stAtom tokens minted) are converted to Atom and are re-delegated back to the validators pool.
Rewards are not converted to ATOM. Reward denoms are filtered for ATOM, and only ATOM is re-delegated (no conversion happens)

2022-03-03 15:07 UTC, ratik commented on contracts/lido_cosmos_rewards_dispatcher/README.md
> +All rewards from stAtom tokens (the share of all rewards proportional to the amount of stAtom tokens minted) are converted to Atom and are re-delegated back to the validators pool.
fixed

2022-03-03 15:07 UTC, ratik commented on contracts/lido_cosmos_validators_registry/src/common.rs
> -    Ok((amount_to_delegate, delegations))
fixed

2022-03-03 17:00 UTC, pr0n00gler commented on contracts/lido_cosmos_validators_registry/src/common.rs
> +            "Amount to delegate greater than zero",
I don't think this is a good error message for a user. Maybe change it to "failed to distribute delegated amount completely" or something?

2022-03-03 17:37 UTC, ratik commented on contracts/lido_cosmos_validators_registry/src/common.rs
> +            "Amount to delegate greater than zero",
updated 👍

2022-03-03 18:15 UTC, foxpy commented on contracts/lido_cosmos_validators_registry/src/common.rs
> -    Ok((amount_to_delegate, delegations))
Is returning error really the best way? Maybe we should spread these leftover coins among all validators? I really don't like the idea of returning error here.

2022-03-03 18:24 UTC, foxpy commented
I still don't like what we have in `NOTICE`: copyrights look wrong.

2022-03-03 18:39 UTC, foxpy reviewed
Not really much happening here compared to previous review iteration.

2022-03-03 19:26 UTC, oopcode commented
> I still don't like what we have in `NOTICE`: copyrights look wrong.
> 
> This has nothing to do with this particular PR, but still…

we'll check it once again

2022-03-04 09:04 UTC, oopcode approved these changes

2022-03-04 09:25 UTC, foxpy commented on contracts/lido_cosmos_validators_registry/src/common.rs
> -    Ok((amount_to_delegate, delegations))
@oopcode I guess I am ready to approve PR after we have answer to my question about returning error if `amount_to_delegate != 0`.

2022-03-04 10:10 UTC, sotnikov-s requested changes

2022-03-04 10:23 UTC, ratik commented on contracts/lido_cosmos_hub/Cargo.toml
>  edition = "2018"
this one is related to Rust edition
<img width="860" alt="image" src="https://user-images.githubusercontent.com/198887/156745859-95f584d4-679c-4fa9-a5a6-6a068739274d.png">
So I think we can keep it 2018

2022-03-04 10:24 UTC, ratik commented on contracts/lido_cosmos_hub/src/bond.rs
> -    // peg recovery fee should be considered
good point 👍 fixed

2022-03-04 10:25 UTC, ratik commented on contracts/lido_cosmos_hub/src/bond.rs
>              .add_messages(external_call_msgs)
good point 👍 fixed

2022-03-04 10:49 UTC, oopcode commented
i've run the feat/moar integration tests on this code, seems like everything's okay. please finalise your reviews : )

2022-03-04 10:49 UTC, sotnikov-s approved these changes

2022-03-04 10:54 UTC, sotnikov-s commented on contracts/lido_cosmos_validators_registry/src/common.rs
> -    Ok((amount_to_delegate, delegations))
@foxpy the `request changes` option is made to help you in this. it's our good practice to use it to prevent unwanted premature merges

2022-03-04 11:25 UTC, foxpy commented on contracts/lido_cosmos_validators_registry/src/common.rs
> -    Ok((amount_to_delegate, delegations))
:thinking: the problem is that I might prevent/delay an actually good merge

2022-03-04 11:26 UTC, foxpy commented on contracts/lido_cosmos_hub/Cargo.toml
>  edition = "2018"
> what is `edition` about? should it be 2018?

You can think of it as of C++ standard

2022-03-04 11:30 UTC, foxpy requested changes

2022-03-04 11:30 UTC, foxpy commented on contracts/lido_cosmos_validators_registry/src/common.rs
> +        Err(StdError::generic_err(
I feel like we can do better than just returning error. Maybe distribute remaining `amount_to_delegate` evenly across every validator?

2022-03-04 11:36 UTC, ratik commented on contracts/lido_cosmos_validators_registry/src/common.rs
> -    Ok((amount_to_delegate, delegations))
so, as @pr0n00gler said it was impossible that `amount_to_delegate` was zero after the loop but it was good idea to add one more check here. And if so we should revert tx (afaik it can be done by throwing error) @foxpy

2022-03-04 11:47 UTC, foxpy commented on contracts/lido_cosmos_validators_registry/src/common.rs
> -    Ok((amount_to_delegate, delegations))
Okay, gotcha, so that's just defensive programming. Maybe we should leave a comment that this error branch shouldn't happen?

2022-03-04 11:49 UTC, foxpy commented on contracts/lido_cosmos_validators_registry/src/common.rs
> -    Ok((amount_to_delegate, delegations))
also @ratik please continue this conversation in thread where I have requested changes.

2022-03-04 11:51 UTC, ratik commented on contracts/lido_cosmos_validators_registry/src/common.rs
> +        Err(StdError::generic_err(
yep, I believe this is kinda double check and I'll add a comment. Good point 👍

2022-03-04 11:53 UTC, oopcode commented on contracts/lido_cosmos_validators_registry/src/common.rs
> +        Err(StdError::generic_err(
> Maybe we should leave a comment that this error branch shouldn't happen?
i vote for this solution; `amount_to_delegate` is never expected  to be zero, and this logic has already been audited; this is a "just in case" thing.

2022-03-04 11:59 UTC, ratik commented on contracts/lido_cosmos_validators_registry/src/common.rs
> +        Err(StdError::generic_err(
I've added the comment

2022-03-04 12:02 UTC, foxpy commented on contracts/lido_cosmos_validators_registry/src/common.rs
> +        Err(StdError::generic_err(
Thank you!

2022-03-04 12:03 UTC, foxpy approved these changes

2022-03-04 12:21 UTC, pr0n00gler approved these changes

2022-03-04 14:11 UTC, swelf19 approved these changes

2022-03-04 15:02 UTC, merged