feat: unbond via vouchers
lidofinance/lido-cosmos-hub-contracts pull request #17
Opened 2022-03-22 14:52 UTC by oopcode

2022-03-28 12:15 UTC, pr0n00gler requested changes
There a lot of unused unbond structs left (`UnbondHistory`, `UnbondHistoryResponse`, `UnbondWaitEntity`, etc).

Also we don't need  `epoch_period` and `unbonding_period` fields in` InstantiateMsg` struct anymore.

2022-03-28 12:15 UTC, pr0n00gler commented on contracts/lido_cosmos_hub/src/tokenized.rs
> +        sender.clone(),
You're setting `tokenise_share_owner` equals to the sender address here to mint tokenise shares for the sender. But according to the [liquidity module's code](https://github.com/iqlusioninc/liquidity-staking-module/blob/faf413d4624af0a6fa8aac2c359d1b1b4f6adbc9/x/staking/keeper/msg_server.go#L447) shares are minted to the module's account and [sent](https://github.com/iqlusioninc/liquidity-staking-module/blob/faf413d4624af0a6fa8aac2c359d1b1b4f6adbc9/x/staking/keeper/msg_server.go#L452) to the **delegator's** account not the owner's.

2022-03-28 12:15 UTC, pr0n00gler commented on contracts/lido_cosmos_hub/src/tokenized.rs
> +    let encoded_tokenize_msg = Binary::from(tokenize_msg.write_to_bytes().unwrap());
Remove `unwrap()` pls

2022-03-28 12:15 UTC, mmikev commented on contracts/lido_cosmos_hub/src/unbond.rs
>  // limitations under the License.
empty file?

2022-03-28 12:41 UTC, pr0n00gler requested changes

2022-03-28 12:41 UTC, pr0n00gler commented on contracts/lido_cosmos_hub/src/tokenized.rs
> +    let config = CONFIG.load(deps.storage)?;
You're reading config twice: here and on L338

2022-03-28 12:41 UTC, pr0n00gler commented on contracts/lido_cosmos_hub/src/tokenized.rs
> +        attr("unbonded_amount", amount),
`undelegation_amount` instead of `amount` maybe?

2022-03-28 12:48 UTC, pr0n00gler commented on contracts/lido_cosmos_hub/src/tokenized.rs
> +        return Err(StdError::generic_err(format!(
Why don't use the same logic like we did before (flat undelegations) but instead of undelegate messages create `tokenize_share_msgs`?

2022-03-28 14:16 UTC, zavgorodnii commented on contracts/lido_cosmos_hub/src/tokenized.rs
> +        return Err(StdError::generic_err(format!(
we sort of copied the way this is done on solana (vasiliy seemed to like this more than the multivoucher option).

2022-03-30 11:54 UTC, pr0n00gler submitted a review, later dismissed

2022-03-30 14:30 UTC, swelf19 commented on packages/basset/src/hub.rs
> +    pub max_burn_ratio: Option<Decimal>,
According to the code base, there is no way to set max_burn_ratio to None. And actually i do not see a reason to make the field optional.

2022-03-30 14:30 UTC, swelf19 commented on contracts/lido_cosmos_hub/src/tokenized.rs
> +        return Err(StdError::generic_err(format!(
In other words, we forced user to make flattering by sending multiple `unbond` messages? What do you think about to make error message a bit clearer, add maximum amount allowed to unbond alongside with max_burn_ratio

2022-03-30 14:30 UTC, swelf19 commented on contracts/lido_cosmos_hub/src/contract.rs
> +        let response_coin = tokenize_shares_response.amount.unwrap();
error handling instead of unwraps?

2022-03-30 14:30 UTC, swelf19 commented on contracts/lido_cosmos_hub/src/tokenized.rs
> +    TOKENIZED_SHARE_RECIPIENT.save(deps.storage, &sender)?;
cant we pass necessary data with a submsg response?

2022-03-30 15:26 UTC, oopcode commented on packages/basset/src/hub.rs
> +    pub max_burn_ratio: Option<Decimal>,
will you be able to read it from storage during migration without making the field optional?

2022-03-30 17:18 UTC, foxpy commented
Guys, there are two lints which prohibit usage of [unwrap](https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_used) and [expect](https://rust-lang.github.io/rust-clippy/master/index.html#expect_used). I suggest enabling them in every file except for tests.

2022-03-30 19:40 UTC, oopcode commented on contracts/lido_cosmos_hub/src/tokenized.rs
> +    TOKENIZED_SHARE_RECIPIENT.save(deps.storage, &sender)?;
i don't think so?..

2022-03-31 12:57 UTC, oopcode commented
> Guys, there are two lints which prohibit usage of [unwrap](https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_used) and [expect](https://rust-lang.github.io/rust-clippy/master/index.html#expect_used). I suggest enabling them in every file except for tests.

this sound good. could you please add a task to our backlog?

2022-03-31 13:04 UTC, foxpy commented
> could you please add a task to our backlog

:heavy_check_mark: Check out card #LSC-307.

2022-03-31 13:12 UTC, swelf19 approved these changes

2022-03-31 13:21 UTC, pr0n00gler approved these changes

2022-03-31 13:34 UTC, merged