fixed: reveive_tokenized_share handler #LSC-337
lidofinance/lido-cosmos-hub-contracts pull request #23
Opened 2022-04-21 09:16 UTC by swelf19

its alive!

I had to fix MockApi. Mocked add_humanize differs from  production one, and method fails in the unit tests when building Addr for a share_module

2022-04-21 09:56 UTC, oopcode commented
yaaaaaay
@ratik can you test it with your testkit?

2022-04-21 13:05 UTC, oopcode commented on contracts/lido_cosmos_hub/src/tokenized.rs
> +    let s = result[..20].to_vec();
please move 20 to a constant

2022-04-21 13:07 UTC, oopcode commented on contracts/lido_cosmos_hub/src/tokenized.rs
> +    hasher.update(module_name);
this code is scary af. i don't see any way to avoid it though...

2022-04-21 13:14 UTC, oopcode commented on contracts/lido_cosmos_hub/src/tokenized.rs
> +    hasher.update(module_name);
looks like guys from cosmwasm use a shortcut: https://github.com/CosmWasm/cosmwasm/blob/e4fd6413e8a54ae4bb9ff2a1e60ef551d03f2927/packages/crypto/benches/main.rs#L81

2022-04-21 19:10 UTC, foxpy commented on contracts/lido_cosmos_hub/src/testing/mock_querier.rs
> +                        )));
That's hell on Earth. Can't we do it in a simpler way? I haven't found a decent solution :(

2022-04-21 19:27 UTC, foxpy requested changes

2022-04-21 19:27 UTC, foxpy commented on contracts/lido_cosmos_hub/src/testing/mock_querier.rs
> +                        )));
`return SystemResult::Ok(ContractResult::Ok(Binary::from(response.write_to_bytes().unwrap())));` :sunglasses:

2022-04-22 07:56 UTC, foxpy approved these changes

2022-04-22 09:18 UTC, oopcode approved these changes

2022-04-22 09:21 UTC, ratik approved these changes

2022-04-22 09:22 UTC, merged